[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    "primitives",
    'runtime',
    'modules/cloverdex',
    'modules/evm-accounts',
    'modules/reward-pool',
    'modules/incentives',
    'modules/traits',
]

[patch.crates-io]
